# Generated by Django 5.1.7 on 2025-03-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status_quarto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status_reserva', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaTipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarifa_tipo_quarto', models.CharField(max_length=255)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_quarto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura_ocorrencia', models.DateField()),
                ('data_fechamento_ocorrencia', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('finalizada', models.BooleanField(default=False)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='status_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.statusquarto'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('data_check_in', models.DateField()),
                ('data_check_out', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.quarto')),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.statusreserva')),
                ('tarifa_tipo_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.tarifatipoquarto')),
            ],
        ),
        migrations.AddField(
            model_name='tarifatipoquarto',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.tipoquarto'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.tipoquarto'),
        ),
    ]
