# Generated by Django 5.1.7 on 2025-04-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifatipoquarto',
            name='valor_diaria',
            field=models.FloatField(default=0),
        ),
    ]
