# Generated by Django 5.1.7 on 2025-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
    ]
