# Generated by Django 5.1.7 on 2025-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_funcionario_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='senha',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
