# Generated by Django 5.1.7 on 2025-03-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_rename_senha_funcionario_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='login',
            new_name='username',
        ),
    ]
