# Generated by Django 5.1.7 on 2025-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_rename_login_funcionario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
