# Generated by Django 5.1.7 on 2025-03-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_funcionario_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='username',
            new_name='usuario',
        ),
    ]
