# Generated by Django 5.1.7 on 2025-03-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_rename_username_funcionario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='usuario',
            new_name='username',
        ),
    ]
