# Generated by Django 5.1.7 on 2025-03-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_rename_usuario_funcionario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='administrador',
        ),
    ]
