# Generated by Django 5.1.7 on 2025-04-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='status_quarto',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='tipo_quarto',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto'),
        ),
        migrations.RemoveField(
            model_name='tarifatipoquarto',
            name='tipo_quarto',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tarifa_tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.tarifatipoquarto'),
        ),
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
        migrations.DeleteModel(
            name='StatusQuarto',
        ),
        migrations.DeleteModel(
            name='Quarto',
        ),
        migrations.DeleteModel(
            name='TipoQuarto',
        ),
        migrations.DeleteModel(
            name='TarifaTipoQuarto',
        ),
    ]
