# Generated by Django 5.1.7 on 2025-05-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_quarto_status_quarto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='quarto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='status_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tarifa_tipo_quarto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='StatusReserva',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
