# Generated by Django 5.1.7 on 2025-04-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status_quarto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_quarto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura_ocorrencia', models.DateField()),
                ('data_fechamento_ocorrencia', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('finalizada', models.BooleanField(default=False)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='status_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.statusquarto'),
        ),
        migrations.CreateModel(
            name='TarifaTipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarifa_tipo_quarto', models.CharField(max_length=255)),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('valor_diaria', models.FloatField(default=0)),
                ('tipo_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.tipoquarto')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.tipoquarto'),
        ),
    ]
