# Generated by Django 5.1.7 on 2025-05-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_abertura_ocorrencia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_fechamento_ocorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
