# Generated by Django 5.1.7 on 2025-05-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_alter_ocorrencia_data_abertura_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='reserva_liberada',
            field=models.BooleanField(default=True),
        ),
    ]
