# Generated by Django 5.1.7 on 2025-07-02 23:59

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0004_alter_ocorrencia_quarto_alter_quarto_status_quarto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/quartos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
