# Generated by Django 5.1.7 on 2025-05-04 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('quartos', '0002_alter_ocorrencia_data_abertura_ocorrencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status_reserva', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('data_check_in', models.DateField()),
                ('data_check_out', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto')),
                ('tarifa_tipo_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.tarifatipoquarto')),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.statusreserva')),
            ],
        ),
    ]
