# Generated by Django 5.1.7 on 2025-05-04 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_reserva',
            new_name='data_reserva_criada',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_reserva_previsao_fim',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_reserva_previsao_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
