# Generated by Django 5.1.7 on 2025-05-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_data_reserva_reserva_data_reserva_criada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data_reserva_criada']},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
