# Generated by Django 5.1.7 on 2025-05-23 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('quartos', '0004_alter_ocorrencia_quarto_alter_quarto_status_quarto_and_more'),
        ('reservas', '0003_alter_reserva_options_alter_reserva_data_check_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.quarto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservas.statusreserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tarifa_tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quartos.tarifatipoquarto'),
        ),
    ]
