# Generated by Django 5.1.7 on 2025-05-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_cliente_alter_reserva_funcionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
