# Generated by Django 5.1.7 on 2025-06-12 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_data_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva_criada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
